# Generated by Django 3.1.7 on 2022-07-26 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_currency_historicalcurrency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='currency',
        ),
        migrations.DeleteModel(
            name='Historicalcurrency',
        ),
    ]
