# Generated by Django 3.1.7 on 2022-07-24 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltasksservices',
            name='idStatusInvoice',
        ),
        migrations.RemoveField(
            model_name='tasksservices',
            name='idStatusInvoice',
        ),
        migrations.AlterField(
            model_name='historicaltasksservices',
            name='idContract',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contracts.customercontractservice'),
        ),
        migrations.AlterField(
            model_name='tasksservices',
            name='idContract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.customercontractservice'),
        ),
    ]
