# Generated by Django 3.1.7 on 2022-07-24 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('customers', '0002_auto_20220723_1025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0010_auto_20220724_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCustomerContractService',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('precio', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True, verbose_name='Precio')),
                ('dateBegin', models.DateField(blank=True, max_length=255, null=True, verbose_name='Fecha Inicio contrato')),
                ('dateEnd', models.DateField(blank=True, max_length=255, null=True, verbose_name='Fecha Inicio contrato')),
                ('dateComputation', models.DateField(blank=True, max_length=255, null=True, verbose_name='Fecha Inicio contrato')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('idCustomer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.customers')),
                ('idOrder', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.salesorder')),
                ('idService', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='services.services', verbose_name='Servicio')),
                ('idTypeSchedule', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='services.typeschedule')),
            ],
            options={
                'verbose_name': 'historical Contrato',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CustomerContractService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('precio', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True, verbose_name='Precio')),
                ('dateBegin', models.DateField(blank=True, max_length=255, null=True, verbose_name='Fecha Inicio contrato')),
                ('dateEnd', models.DateField(blank=True, max_length=255, null=True, verbose_name='Fecha Inicio contrato')),
                ('dateComputation', models.DateField(blank=True, max_length=255, null=True, verbose_name='Fecha Inicio contrato')),
                ('idCustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customers')),
                ('idOrder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.salesorder')),
                ('idService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.services', verbose_name='Servicio')),
                ('idTypeSchedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.typeschedule')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
    ]
