# Generated by Django 3.1.7 on 2022-07-25 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercontractservice',
            name='idOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.salesorder'),
        ),
        migrations.AlterField(
            model_name='customercontractservice',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='historicalcustomercontractservice',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True, verbose_name='Precio'),
        ),
    ]
