# Generated by Django 3.1.7 on 2022-07-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20220725_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercontractservice',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='historicalcustomercontractservice',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio'),
        ),
    ]
