# Generated by Django 3.1.7 on 2022-07-25 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20220723_1025'),
        ('orders', '0001_initial'),
        ('services', '0011_auto_20220724_1854'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0005_auto_20220725_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeContract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo contrato',
                'verbose_name_plural': 'Tipos contrato',
            },
        ),
        migrations.RemoveField(
            model_name='customercontractservice',
            name='idTypeSchedule',
        ),
        migrations.RemoveField(
            model_name='historicalcustomercontractservice',
            name='idTypeSchedule',
        ),
        migrations.AlterField(
            model_name='customercontractservice',
            name='dateComputation',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='Fecha Proceso contrato'),
        ),
        migrations.AlterField(
            model_name='customercontractservice',
            name='dateEnd',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='Fecha Vencimiento contrato'),
        ),
        migrations.AlterField(
            model_name='customercontractservice',
            name='idCustomer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customers', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='customercontractservice',
            name='idOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.salesorder', verbose_name='Orden de compra'),
        ),
        migrations.AlterField(
            model_name='customercontractservice',
            name='idService',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.services', verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='historicalcustomercontractservice',
            name='dateComputation',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='Fecha Proceso contrato'),
        ),
        migrations.AlterField(
            model_name='historicalcustomercontractservice',
            name='dateEnd',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='Fecha Vencimiento contrato'),
        ),
        migrations.AlterField(
            model_name='historicalcustomercontractservice',
            name='idCustomer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.customers', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='historicalcustomercontractservice',
            name='idOrder',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.salesorder', verbose_name='Orden de compra'),
        ),
        migrations.AlterField(
            model_name='historicalcustomercontractservice',
            name='idService',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='services.services', verbose_name='Servicio'),
        ),
        migrations.CreateModel(
            name='HistoricalTypeContract',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Tipo contrato',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='customercontractservice',
            name='idTypeContract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.typecontract', verbose_name='Tipo contrato'),
        ),
        migrations.AddField(
            model_name='historicalcustomercontractservice',
            name='idTypeContract',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contracts.typecontract', verbose_name='Tipo contrato'),
        ),
    ]
