# Generated by Django 3.1.7 on 2022-07-25 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20220723_1025'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsalesorder',
            name='idEnterprice',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.enterprice', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='idEnterprice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.enterprice', verbose_name='Empresa'),
        ),
    ]
