# Generated by Django 3.1.7 on 2022-07-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20220725_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsalesorder',
            name='numero',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número orden'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='numero',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número orden'),
        ),
    ]
