# Generated by Django 3.1.7 on 2022-07-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20220725_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsalesorder',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='amount',
        ),
        migrations.AddField(
            model_name='historicalsalesorder',
            name='amountHour',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True, verbose_name='Monto'),
        ),
        migrations.AddField(
            model_name='historicalsalesorder',
            name='amountTotal',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True, verbose_name='Monto'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='amountHour',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True, verbose_name='Monto'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='amountTotal',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True, verbose_name='Monto'),
        ),
    ]
