# Generated by Django 3.1.7 on 2022-07-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20220725_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsalesorder',
            name='amountTotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Total'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='amountTotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Total'),
        ),
    ]
