# Generated by Django 3.1.7 on 2022-07-26 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
        ('orders', '0007_auto_20220725_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsalesorder',
            name='idCurrency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parameters.currency', verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='idCurrency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parameters.currency', verbose_name='Moneda'),
        ),
    ]
