# Generated by Django 3.1.7 on 2022-07-26 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20220724_1854'),
        ('orders', '0008_auto_20220725_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsalesorder',
            name='idService',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='services.services', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='idService',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.services', verbose_name='Empresa'),
        ),
    ]
