# Generated by Django 3.1.7 on 2022-07-15 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalservices',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Servicio'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.RemoveField(
            model_name='historicalservices',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='services',
            name='phone',
        ),
    ]
