# Generated by Django 3.1.7 on 2022-07-15 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20220715_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltypeservice',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='TypeService',
        ),
        migrations.AlterModelOptions(
            name='historicaltypeschedule',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Tipo facturación'},
        ),
        migrations.AlterModelOptions(
            name='typeschedule',
            options={'verbose_name': 'Tipo facturación', 'verbose_name_plural': 'Tipo facturaciones'},
        ),
        migrations.DeleteModel(
            name='HistoricalTypeService',
        ),
    ]
