# Generated by Django 3.1.7 on 2022-07-16 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_historicaltasksservices_tasksservices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customercontractservice',
            options={'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.AlterModelOptions(
            name='historicalcustomercontractservice',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Contrato'},
        ),
        migrations.AlterModelOptions(
            name='historicaltasksservices',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Tarea'},
        ),
        migrations.AlterModelOptions(
            name='tasksservices',
            options={'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.AlterField(
            model_name='customercontractservice',
            name='idService',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.services', verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='historicalcustomercontractservice',
            name='idService',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='services.services', verbose_name='Servicio'),
        ),
    ]
