# Generated by Django 3.1.7 on 2022-07-19 03:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0005_auto_20220715_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('amount', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True, verbose_name='Monto')),
                ('numberHours', models.IntegerField(blank=True, null=True, verbose_name='Horas')),
                ('date', models.DateField(blank=True, max_length=255, null=True, verbose_name='Fecha orden')),
            ],
            options={
                'verbose_name': 'Order de compra',
                'verbose_name_plural': 'Ordenes de compra',
            },
        ),
        migrations.CreateModel(
            name='StatusInvoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Estado facturación',
                'verbose_name_plural': 'Estados facturacion',
            },
        ),
        migrations.AddField(
            model_name='customercontractservice',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True, verbose_name='Precio'),
        ),
        migrations.AddField(
            model_name='historicalcustomercontractservice',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='historicaltasksservices',
            name='timeSpendHoras',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)], verbose_name='Horas gastadas'),
        ),
        migrations.AlterField(
            model_name='historicaltasksservices',
            name='timeSpendMinutos',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)], verbose_name='Minutos gastados'),
        ),
        migrations.AlterField(
            model_name='tasksservices',
            name='timeSpendHoras',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)], verbose_name='Horas gastadas'),
        ),
        migrations.AlterField(
            model_name='tasksservices',
            name='timeSpendMinutos',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)], verbose_name='Minutos gastados'),
        ),
        migrations.CreateModel(
            name='HistoricalStatusInvoice',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Estado facturación',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSalesOrder',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('amount', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True, verbose_name='Monto')),
                ('numberHours', models.IntegerField(blank=True, null=True, verbose_name='Horas')),
                ('date', models.DateField(blank=True, max_length=255, null=True, verbose_name='Fecha orden')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Order de compra',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='customercontractservice',
            name='idOrder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.salesorder'),
        ),
        migrations.AddField(
            model_name='historicalcustomercontractservice',
            name='idOrder',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='services.salesorder'),
        ),
        migrations.AddField(
            model_name='historicaltasksservices',
            name='idStatusInvoice',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='services.statusinvoice'),
        ),
        migrations.AddField(
            model_name='tasksservices',
            name='idStatusInvoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.statusinvoice'),
        ),
    ]
