# Generated by Django 3.1.7 on 2022-07-24 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20220723_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinvoicescontracts',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalinvoicescontracts',
            name='idContract',
        ),
        migrations.RemoveField(
            model_name='historicalinvoicescontracts',
            name='idInvoiceDocument',
        ),
        migrations.RemoveField(
            model_name='historicalinvoicescontracts',
            name='idStatusInvoice',
        ),
        migrations.RemoveField(
            model_name='historicalinvoicescontracts',
            name='idTask',
        ),
        migrations.RemoveField(
            model_name='historicaltasksservices',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltasksservices',
            name='idContract',
        ),
        migrations.RemoveField(
            model_name='historicaltasksservices',
            name='idStatusInvoice',
        ),
        migrations.RemoveField(
            model_name='historicaltasksservices',
            name='idStatusTask',
        ),
        migrations.RemoveField(
            model_name='historicaltasksservices',
            name='idUser',
        ),
        migrations.RemoveField(
            model_name='invoicedocument',
            name='idEnterpriceCustomer',
        ),
        migrations.RemoveField(
            model_name='invoicedocument',
            name='idSalesOrder',
        ),
        migrations.RemoveField(
            model_name='invoicescontracts',
            name='idContract',
        ),
        migrations.RemoveField(
            model_name='invoicescontracts',
            name='idInvoiceDocument',
        ),
        migrations.RemoveField(
            model_name='invoicescontracts',
            name='idStatusInvoice',
        ),
        migrations.RemoveField(
            model_name='invoicescontracts',
            name='idTask',
        ),
        migrations.RemoveField(
            model_name='tasksservices',
            name='idContract',
        ),
        migrations.RemoveField(
            model_name='tasksservices',
            name='idStatusInvoice',
        ),
        migrations.RemoveField(
            model_name='tasksservices',
            name='idStatusTask',
        ),
        migrations.RemoveField(
            model_name='tasksservices',
            name='idUser',
        ),
        migrations.DeleteModel(
            name='HistoricalInvoiceDocument',
        ),
        migrations.DeleteModel(
            name='HistoricalInvoicesContracts',
        ),
        migrations.DeleteModel(
            name='HistoricalTasksServices',
        ),
        migrations.DeleteModel(
            name='InvoiceDocument',
        ),
        migrations.DeleteModel(
            name='InvoicesContracts',
        ),
        migrations.DeleteModel(
            name='TasksServices',
        ),
    ]
