# Generated by Django 3.1.7 on 2022-07-24 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20220724_1854'),
        ('services', '0010_auto_20220724_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercontractservice',
            name='idCustomer',
        ),
        migrations.RemoveField(
            model_name='customercontractservice',
            name='idOrder',
        ),
        migrations.RemoveField(
            model_name='customercontractservice',
            name='idService',
        ),
        migrations.RemoveField(
            model_name='customercontractservice',
            name='idTypeSchedule',
        ),
        migrations.RemoveField(
            model_name='historicalcustomercontractservice',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcustomercontractservice',
            name='idCustomer',
        ),
        migrations.RemoveField(
            model_name='historicalcustomercontractservice',
            name='idOrder',
        ),
        migrations.RemoveField(
            model_name='historicalcustomercontractservice',
            name='idService',
        ),
        migrations.RemoveField(
            model_name='historicalcustomercontractservice',
            name='idTypeSchedule',
        ),
        migrations.RemoveField(
            model_name='historicalsalesorder',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalstatusinvoice',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalstatustask',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='StatusInvoice',
        ),
        migrations.DeleteModel(
            name='StatusTask',
        ),
        migrations.DeleteModel(
            name='CustomerContractService',
        ),
        migrations.DeleteModel(
            name='HistoricalCustomerContractService',
        ),
        migrations.DeleteModel(
            name='HistoricalSalesOrder',
        ),
        migrations.DeleteModel(
            name='HistoricalStatusInvoice',
        ),
        migrations.DeleteModel(
            name='HistoricalStatusTask',
        ),
        migrations.DeleteModel(
            name='SalesOrder',
        ),
    ]
